FROM centos:7
ENV CLOTO_SETTINGS_FILE /etc/fiware.d/fiware-cloto.cfg
RUN yum groupinstall -y 'development tools'
RUN yum install -y python-devel MySQL-python mysql-devel nmap
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py
RUN pip install supervisor
RUN git clone https://github.com/telefonicaid/fiware-cloto /opt/fiware-cloto
WORKDIR /opt/fiware-cloto
RUN mkdir /etc/fiware.d/
RUN mkdir /var/log/fiware-cloto
RUN pip install -r requirements.txt
COPY fiware-cloto.cfg /etc/fiware.d/fiware-cloto.cfg
RUN cp utils/cloto_start /etc/fiware.d/
RUN chmod a+x /etc/fiware.d/cloto_start
RUN mkdir -p /etc/supervisor/conf.d
RUN cp utils/fiware-cloto.conf /etc/supervisor/conf.d
COPY start_centos7.sh start_centos7.sh
CMD ./start_centos7.sh
