#!/bin/sh
# -*- encoding: utf-8 -*-
#
# Copyright 2014 Telefónica Investigación y Desarrollo, S.A.U
#
# This file is part of FI-WARE project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For those usages not covered by the Apache version 2.0 License please
# contact with opensource@tid.es
#
#
# fiware-cloto

### BEGIN INIT INFO
# Provides:
# Short-Description: Execute fiware-cloto server
# Description: Execute fiware-cloto server
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=run.sh

start() {
    sh $prog
}

stop() {
    kill -9 `ps awx | grep '/fiware_cloto/' | grep -v grep | awk '{print $1}'`
    kill -9 `ps awx | grep '/fiware-cloto/' | grep -v grep | awk '{print $1}'`
}

restart() {
    stop
    sleep 5
    start
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
exit $?
